Homework adding movie_details_activity
prometey-dev/AcademyApp pull request #1
Opened 2020-11-20 10:48 UTC by prometey-dev

Добавлена новая активити movie_details_activity.
Экран свёрстан в соответствии с дизайном из figma.

Внешний вид экрана в portrait ориентации:
![image](https://user-images.githubusercontent.com/6102319/99790999-00685d00-2b36-11eb-86b6-80489046be4a.png)

Внешний вид экрана в landscape ориентации:
![image](https://user-images.githubusercontent.com/6102319/99791224-60f79a00-2b36-11eb-912d-2e25257ba956.png)
![image](https://user-images.githubusercontent.com/6102319/99791452-b338bb00-2b36-11eb-8208-d6d03d5ef635.png)

2020-11-20 19:20 UTC, emartynov requested changes
Оформление ПР 5! Можно еще добавить линк на фигму для полноты. Посмотри еще на поддержку markdown.

Общие комментарии:
* В ПР смешаны изменения по заданию и общие улучшения с проектом (gitignore). Чище это делать в разных ПР.
* mipmap используется только для иконок приложения. Также фигма позволяет экспорт картинок для разного разрешения.
* Все размеры чище вынести в ресурс файлы и переиспользовать.

Заношу домашку, но жду изменений. ***Удачи!***

2020-11-20 19:20 UTC, emartynov commented on .gitignore
> +/.idea
Ну так удали же файлы из гита тогда :)

2020-11-20 19:20 UTC, emartynov commented on app/src/main/res/layout/activity_movie_details.xml
> +<androidx.core.widget.NestedScrollView xmlns:android="http://schemas.android.com/apk/res/android"
Почему NestedScrollView а не просто ScrollView?

2020-11-20 19:20 UTC, emartynov commented on app/src/main/res/layout/activity_movie_details.xml
> +        android:layout_height="match_parent"
wrap_content

2020-11-20 19:20 UTC, emartynov commented on app/src/main/res/layout/activity_movie_details.xml
> +    android:layout_height="wrap_content">
match_parent

2020-11-20 19:20 UTC, emartynov commented on app/src/main/res/layout/activity_movie_details.xml
> +        <androidx.appcompat.widget.AppCompatImageView
ImageView достаточно

2020-11-20 19:20 UTC, emartynov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_width="match_parent"
Сделай 0dp,  но привяжи правую границу к родителю и посмотри что будет

2020-11-20 19:20 UTC, emartynov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:adjustViewBounds="true"
Используе constraintAspectRation вместо этого после 0dp изменений

2020-11-20 19:20 UTC, emartynov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_marginTop="56dp"
Выноси все размеры в dimens.xml

2020-11-20 19:20 UTC, emartynov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:textSize="12sp"
Опционно посмотри на стили в андроиде

2020-11-20 19:20 UTC, emartynov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_marginTop="222dp"
Лучше использовать Guideline с процентным положением

2020-11-20 19:20 UTC, emartynov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:theme="@style/MyRatingBar"
Вау, и стиль и тема - почему?

2020-11-20 19:20 UTC, emartynov commented on app/src/main/res/layout/activity_movie_details.xml
> +            app:layout_constraintTop_toBottomOf="@id/storyline"/>
А где горизонтальные констрейнты?

2020-11-20 19:20 UTC, emartynov commented on app/src/main/res/values/styles.xml
> +    <style name="AppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar"/>
Не забудь повторить в ночной теме тоже

2020-11-21 08:22 UTC, prometey-dev commented on app/src/main/res/layout/activity_movie_details.xml
> +<androidx.core.widget.NestedScrollView xmlns:android="http://schemas.android.com/apk/res/android"
Тут, конечно с NestedScrollView ошибся, т.к. он обычно используется для скроллирования вложенных в него элементов, в нашем случае это лишнее, так что заменю на ScrollView.

2020-11-21 08:50 UTC, prometey-dev commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:theme="@style/MyRatingBar"
Тут стиль в RatingBar применяется и как стиль и как тема, потому что андроид по другому не воспринимает часть параметров типа colorControlNormal и т.д. Если например убрать style="?android:attr/ratingBarStyleSmall", оставить только тему, то звёздочки по дефолту большими будут. У меня после опытов с RatingBar, только так нормально отобразилось.

2020-11-21 09:30 UTC, prometey-dev commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:theme="@style/MyRatingBar"
Если просто в стиле определить родителя parent="android:style/Widget.Material.RatingBar.Small", а в аттрибутах RatingBar указать этот style, а тему не указывать, то цвет активной звёздочки по дефолту colorControlActive не применяется, а если указать только тему (задать стиль этот в теме), то звёздочки большие всеравно. Поэтому нормально только при одновременном указании стиля и темы заработало.

2020-11-21 16:28 UTC, prometey-dev reviewed
1)Заменил NestedScrollView на ScrollView
2) У View элементов вынес часть аттрибутов в стили
3) Размеры вынес в ресурсы
4) Добавил горизонтальные констрейнты, где это нужно
5) Картинки вынес в drawable под разные разрешения, экспортировал из фигмы изображения разных рамеров. Из mipmap соответственно удалил их, которые были.

2020-11-21 18:49 UTC, emartynov approved these changes

2020-11-21 19:41 UTC, merged